import { Inter } from "next/font/google";
import './globals.css'
import { Providers } from "./GlobalRedux/provider";
import Navbar from '../components/navbar/navbar'
import Footer from '../components/footer'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
